version: '3.8'

services:
  db-fimas:
    image: postgres:18-alpine
    container_name: db-fimas
    environment:
      POSTGRES_DB: fimas
      POSTGRES_USER: fimas
      POSTGRES_PASSWORD: fimas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: always

  fimas:
#    build: .                    # собирает образ из Dockerfile
    image: fimas:latest
    container_name: fimas-app
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: fimas
      SPRING_DATASOURCE_PASSWORD: fimas
    depends_on:
      - db-fimas
    restart: unless-stopped

volumes:
  postgres_data: