-- V20260330__add_zone_entity_and_policy_zones.sql

-- =============================================
-- 1. Создание таблицы Zone
-- =============================================
CREATE TABLE zone (
                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name        VARCHAR(80)  NOT NULL UNIQUE,
                      description VARCHAR(500),
                      priority    INTEGER      NOT NULL
);

-- =============================================
-- 2. Создание таблицы для ElementCollection (interfaces)
-- =============================================
CREATE TABLE zone_interfaces (
                                 zone_id         BIGINT       NOT NULL,
                                 interface_name  VARCHAR(100) NOT NULL,

                                 PRIMARY KEY (zone_id, interface_name),
                                 CONSTRAINT fk_zone_interfaces_zone
                                     FOREIGN KEY (zone_id) REFERENCES zone(id) ON DELETE CASCADE
);

-- =============================================
-- 3. Добавление колонок для зон в таблицу policy
-- =============================================
ALTER TABLE policy
    ADD COLUMN src_zone_id BIGINT;

ALTER TABLE policy
    ADD COLUMN dst_zone_id BIGINT;

-- =============================================
-- 4. Добавление внешних ключей (с возможностью NULL)
-- =============================================
ALTER TABLE policy
    ADD CONSTRAINT fk_policy_src_zone
        FOREIGN KEY (src_zone_id) REFERENCES zone(id) ON DELETE SET NULL;

ALTER TABLE policy
    ADD CONSTRAINT fk_policy_dst_zone
        FOREIGN KEY (dst_zone_id) REFERENCES zone(id) ON DELETE SET NULL;

-- =============================================
-- 5. Создание зоны по умолчанию ANY (рекомендуется)
-- =============================================
INSERT INTO zone (name, description, priority)
VALUES ('ANY', 'Любая зона (по умолчанию)', 0)
ON CONFLICT (name) DO NOTHING;

-- Опционально: можно добавить пару интерфейсов для ANY, если нужно
INSERT INTO zone_interfaces (zone_id, interface_name)
SELECT id, 'any' FROM zone WHERE name = 'ANY'
ON CONFLICT DO NOTHING;